name: CI/CD Pipeline

on:
  pull_request:
    types: [closed]
    branches: ["master"]
  push:
    branches: [ "master" ]

jobs:
  test:
    if: github.event.pull_request.merged == true || github.event == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - name: Install dependencies
        run: go mod tidy
      - name: Build
        run: make compile
      - name: Test with the Go CLI
        run: make test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to production server
      run: |
        rsync -avz --exclude '.git*' -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.PROJECT_PATH }}

    - name: Build and run Docker container on production
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd ${{ secrets.PROJECT_PATH }}
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build app migrate
        EOF